### ISSUE TITLE
switchboard-utils issue when compiling for aarch64

### ISSUE THREAD

**Issue by shjort** [blockworks-foundation/liquidatable-accounts-feed#1]
Hey guys,

I've been trying to compile for aarch64 without success due to error regarding switchboard-utils. 
```
error[E0080]: evaluation of constant value failed
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/switchboard-utils-0.1.32/src/lib.rs:19:18
   |
19 | #[derive(Default,AsBytes,FromBytes,Clone,Debug)]
   |                  ^^^^^^^ attempt to divide `1_usize` by zero
   |
   = note: this error originates in the derive macro `AsBytes` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `switchboard-utils` due to previous error
warning: build failed, waiting for other jobs to finish...
^[ error: build failed
```
No trouble on x86 though. 

I tried forcing a later version of switchboard-utils which compiled but bricked other dependencies. Known issue? Suggestions for a solution?

Best regards,
shjort

**Comment by namnh06** [comment]
After the issue above was fixed, I've got this issue:
![image](https://user-images.githubusercontent.com/28762252/164013684-f70a55f0-6029-477d-ba2a-106983768d40.png)

**Comment by ckamm** [comment]
Thanks for the reports! aarch64 is not supported -- a lot of the program code assumes it's on x86, where the on-chain data layouts will match the layout of client structs. I'll add to the readme.
